env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - 'airbnb-base'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  ecmaVersion: 13
rules: {
  no-console: 0,
  import/extensions: 0
}
